language: node_js
cache: yarn
notifications:
  email: false
node_js:
  - '9'
  - '8'
before_scripts:
  - yarn test
  - yarn lint
  - yarn prettier
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
